[package]
name = "moq-trace"
description = "LTTng-UST tracing for MoQ relay object and QUIC packet latency."
authors = ["Luke Curley"]
repository = "https://github.com/moq-dev/moq"
license = "MIT OR Apache-2.0"

version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[features]
default = []
lttng = ["dep:moq-trace-lttng-sys"]

[dependencies]
moq-trace-lttng-sys = { workspace = true, optional = true }
